openapi: 3.0.1
info:
  title: FredsAPI
  version: '0.1'
  description: "Fred's API for the training"
  termsOfService: https://www.example.com/tos
  contact:
    name: Fredrik
    email: test@example.com
    url: https://www.example.com
servers:
  - url: https://my-json-server.typicode.com/gbfredrik/api-design-course/
    variables: {}
    description: "Fred's own mock DB server"
  - url: http://localhost:3000/
    variables: {}
    description: Local server
paths:
  /posts:
    summary: posts
    description: Posts within the db
    get:
      summary: fetch posts
      description: fetch posts from server
      operationId: fetchPosts
      responses:
        default:
          description: Default error sample response
      tags:
        - posts
    post:
      summary: create new post
      description: store a new post on the server
      operationId: createPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostBody'
      responses:
        2XX:
          description: successful post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostBody'
        default:
          description: Default error sample response
      tags:
        - posts
  /posts/{postId}:
    get:
      summary: get specific post
      description: Gets a post for a specific id
      operationId: fetchPostById
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
            minimum: 0
            example: 1
      responses:
        default:
          description: Default error sample response
      tags:
        - posts
components:
  schemas:
    PostBody:
      type: object
      properties:
        title:
          type: string
          example: "Here's your new post"
